force-app/main/default/objects/Log_Detail__c/Log_Detail__c.object-meta.xml
<CustomObject>
    <label>Log Detail</label>
    <nameField>
        <displayFormat>Log - {0000}</displayFormat>
        <label>Log Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Detail__c/fields/Apex_Log_Id__c.field-meta.xml
<CustomField>
    <fullName>Apex_Log_Id__c</fullName>
    <label>Apex Log Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Detail__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Detail__c/fields/Log_Length__c.field-meta.xml
<CustomField>
    <fullName>Log_Length__c</fullName>
    <label>Log Length</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Detail__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>API</fullName>
                <label>Request came from an API</label>
            </value>
            <value>
                <fullName>Application</fullName>
                <label>Request came from the Salesforce user interface</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log_Detail__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Detail__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Detail__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Log_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/Log_Entry_Event__e.object-meta.xml
<CustomObject>
    <label>Log Entry Event</label>
    <pluralLabel>Log Entry Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Entry_Event__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogEntryEventTriggerHelper.cls
public class LogEntryEventTriggerHelper {
    
    public static Map<String, List<Log_Entry_Event__e>> transactionIdToEntries = new Map<String, List<Log_Entry_Event__e>>();
    public static Map<String, Log_Detail__c> transactionIdToLogDetail = new Map<String, Log_Detail__c>();
    
    public static void handleNewPublishedEvent(List<Log_Entry_Event__e> newEvents) {
        for(Log_Entry_Event__e event : newEvents) {
            if(transactionIdToEntries.containsKey(event.Transaction_Id__c)) {
                List<Log_Entry_Event__e> newList = transactionIdToEntries.get(event.Transaction_Id__c);
                newList.add(event);
                transactionIdToEntries.put(event.Transaction_Id__c, newList); 
            }else {
                transactionIdToEntries.put(event.Transaction_Id__c, new List<Log_Entry_Event__e>{event});
            }
        }
        if(!transactionIdToEntries.isEmpty()) {
            for(String transactionId : transactionIdToEntries.keySet()) {
                if(transactionIdToEntries.get(transactionId) != null && !transactionIdToEntries.get(transactionId).isEmpty()) {
                   new LogEntryHandlerJob(transactionId, transactionIdToEntries.get(transactionId)).execute();
                }
            }
        }
    }
    
    /* This method will be called from LogEntryHandlerJob to create the LogDetail record from ApexLog. */
    public static Log_Detail__c createLogDetail(List<ApexLog> apexLogs) {
        try {
            Log_Detail__c newLogDetail = new Log_Detail__c();
            newLogDetail.Duration__c = 0;
            newLogDetail.Log_Length__c = 0;
            for(ApexLog log : apexLogs) {
                newLogDetail.Duration__c = log.DurationMilliseconds;
                newLogDetail.Log_Length__c = log.LogLength;
                newLogDetail.Request_Type__c = log.Request;
                newLogDetail.Start_Time__c = log.StartTime;
                newLogDetail.Status__c = log.Status;
                newLogDetail.Transaction_Id__c = log.RequestIdentifier;
                newLogDetail.User__c = log.LogUserId;
                //newLogDetail.Apex_Log_Id__c = log.Id;
            }
            insert newLogDetail;
            return newLogDetail;
        }catch(Exception ex) {
            return null;
        }
    }
}