force-app/main/default/objects/Log_Entry_Event__e/Log_Entry_Event__e.object-meta.xml
<CustomObject>
    <label>Log Entry Event</label>
    <pluralLabel>Log Entry Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Entry_Event__e/fields/Aggregate_Queries__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Queries__c</fullName>
    <label>Aggregate Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Aggregate_Queries_Limit__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Queries_Limit__c</fullName>
    <label>Aggregate Queries Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Async_Calls__c.field-meta.xml
<CustomField>
    <fullName>Async_Calls__c</fullName>
    <label>Async Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Async_Calls_Limit__c.field-meta.xml
<CustomField>
    <fullName>Async_Calls_Limit__c</fullName>
    <label>Async Calls Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Callouts__c.field-meta.xml
<CustomField>
    <fullName>Callouts__c</fullName>
    <label>Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Callouts_Limit__c.field-meta.xml
<CustomField>
    <fullName>Callouts_Limit__c</fullName>
    <label>Callouts Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/CPU_Time__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time__c</fullName>
    <label>CPU Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/CPU_Time_Limit__c.field-meta.xml
<CustomField>
    <fullName>CPU_Time_Limit__c</fullName>
    <label>CPU Time Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/DML_Rows__c.field-meta.xml
<CustomField>
    <fullName>DML_Rows__c</fullName>
    <label>DML Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/DML_Rows_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Rows_Limit__c</fullName>
    <label>DML Rows Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements__c</fullName>
    <label>DML Statements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/DML_Statements_Limit__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements_Limit__c</fullName>
    <label>DML Statements Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Email_Invocations__c.field-meta.xml
<CustomField>
    <fullName>Email_Invocations__c</fullName>
    <label>Email Invocations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Email_Invocations_Limit__c.field-meta.xml
<CustomField>
    <fullName>Email_Invocations_Limit__c</fullName>
    <label>Email Invocations Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Entry__c.field-meta.xml
<CustomField>
    <fullName>Entry__c</fullName>
    <label>Entry #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Future_Calls__c.field-meta.xml
<CustomField>
    <fullName>Future_Calls__c</fullName>
    <label>Future Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Future_Calls_Limit__c.field-meta.xml
<CustomField>
    <fullName>Future_Calls_Limit__c</fullName>
    <label>Future Calls Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Heap_Size__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size__c</fullName>
    <label>Heap Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Heap_Size_Limit__c.field-meta.xml
<CustomField>
    <fullName>Heap_Size_Limit__c</fullName>
    <label>Heap Size Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Parent_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Transaction_Id__c</fullName>
    <label>Parent Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Query_Locator_Rows__c.field-meta.xml
<CustomField>
    <fullName>Query_Locator_Rows__c</fullName>
    <label>Query Locator Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Query_Locator_Rows_Limit__c.field-meta.xml
<CustomField>
    <fullName>Query_Locator_Rows_Limit__c</fullName>
    <label>Query Locator Rows Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Query_Rows__c.field-meta.xml
<CustomField>
    <fullName>Query_Rows__c</fullName>
    <label>Query Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Query_Rows_Limit__c.field-meta.xml
<CustomField>
    <fullName>Query_Rows_Limit__c</fullName>
    <label>Query Rows Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Queueable_Jobs__c.field-meta.xml
<CustomField>
    <fullName>Queueable_Jobs__c</fullName>
    <label>Queueable Jobs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Queueable_Jobs_Limit__c.field-meta.xml
<CustomField>
    <fullName>Queueable_Jobs_Limit__c</fullName>
    <label>Queueable Jobs Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/SOQL_Queries__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries__c</fullName>
    <label>SOQL Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/SOQL_Queries_Limit__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries_Limit__c</fullName>
    <label>SOQL Queries Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/SOSL_Queries__c.field-meta.xml
<CustomField>
    <fullName>SOSL_Queries__c</fullName>
    <label>SOSL Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/SOSL_Queries_Limit__c.field-meta.xml
<CustomField>
    <fullName>SOSL_Queries_Limit__c</fullName>
    <label>SOSL Queries Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Entry_Event__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger.cls
public class Logger {
    
    private static List<Log_Entry_Event__e> entries = new  List<Log_Entry_Event__e>();
    private static Integer entry = 1;
    private static String origin = '';
    public static String componentType = 'APEX';
    public static String flowAPIName;
    
    public static void debug(String message) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex.getStackTraceString();
            log(message, 'DEBUG');
        }
    }
    
    public static void debug(String message, Id recordId) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex.getStackTraceString();
            log(message, recordId, 'DEBUG');
        }
    }
    
    public static void debug(String message, sObject sObj) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex.getStackTraceString();
            log(message, sObj, 'DEBUG');
        }
    }
    
    public static void debug(String message, List<sObject> listOfSobj) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex.getStackTraceString();
            log(message, listOfSobj, 'DEBUG');
        }
    }
    
    public static void error(String message) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex.getStackTraceString();
            log(message, 'ERROR');
        }
    }
    
    public static void error(String message, Id recordId) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex.getStackTraceString();
            log(message, recordId, 'ERROR');
        }
    }
    
    public static void error(String message, sObject sObj) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex.getStackTraceString();
            log(message, sObj, 'ERROR');
        }
    }
    
    public static void error(String message, List<sObject> listOfSobj) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex.getStackTraceString();
            log(message, listOfSobj, 'ERROR');
        }
    }
    
    public static void error(Exception ex) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex1) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex1.getStackTraceString();
            log(ex.getMessage(), 'EXCEPTION');
        }
    }
    
    public static void error(Exception ex, String recordId) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex1) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex1.getStackTraceString();
            log(ex.getMessage(), recordId, 'EXCEPTION');
        }
    }
    
    public static void error(Exception ex, sObject sObj) {
        try {
           throw new LoggerException(); 
        }catch(Exception ex1) {
            origin = String.isNotBlank(flowAPIName) ? flowAPIName : ex1.getStackTraceString();
            log(ex.getMessage(), sObj, 'EXCEPTION');
        }
    }
        
    private static void log(String message, String level) {
        entries.add(new Log_Entry_Event__e(Transaction_Id__c = Request.getCurrent().getRequestId(),
                                           Message__c = message,
                                           Entry__c = entry++,
                                           Level__c = level,
                                           Type__c = 'LogEntry',
                                           Origin__c = origin,
                                           User_Name__c = UserInfo.getUserName(),
                                           Component_Type__c = componentType));
    }
    
    private static void log(String message, Id recordId, String level) {
        entries.add(new Log_Entry_Event__e(Record_Id__c = recordId, 
                                           Transaction_Id__c = Request.getCurrent().getRequestId(),
                                           Message__c = message,
                                           Entry__c = entry++,
                                           Level__c = level,
                                           Type__c = 'LogEntry',
                                           Origin__c = origin,
                                           User_Name__c = UserInfo.getUserName(),
                                           Component_Type__c = componentType));
    }
    
    private static void log(String message, sObject sObj, String level) {
        if(String.isBlank(sObj.Id)) {
            return;
        }
        entries.add(new Log_Entry_Event__e(Record_Id__c = sObj.Id, 
                                           Transaction_Id__c = Request.getCurrent().getRequestId(),
                                           Message__c = message,
                                           Entry__c = entry++,
                                           Level__c = level,
                                           Type__c = 'LogEntry',
                                           Origin__c = origin,
                                           User_Name__c = UserInfo.getUserName(),
                                           Component_Type__c = componentType));
    }
    
    private static void log(String message, List<sObject> listOfSobj, String level) {
        if(listOfSobj.isEmpty()) {
            return;
        }
        for(sObject sObj : listOfSobj) {
            if(String.isBlank(sObj.Id)) {
                continue;
            }
            entries.add(new Log_Entry_Event__e(Record_Id__c = sObj.Id, 
                                               Transaction_Id__c = Request.getCurrent().getRequestId(),
                                               Message__c = message,
                                               Entry__c = entry++,
                                               Level__c = level,
                                               Type__c = 'LogEntry',
                                               Origin__c = origin,
                                               User_Name__c = UserInfo.getUserName(),
                                               Component_Type__c = componentType));
        }
    }
    
    public static String getTransactionId() {
        return Request.getCurrent().getRequestId();
    }
    
    public static void setParentTransactionId(String transactionId) {
        entries.add(new Log_Entry_Event__e(Transaction_Id__c = Request.getCurrent().getRequestId(),
                                           Parent_Transaction_Id__c = transactionId,
                                           Type__c = 'MappingParent'));
    }
    
    public static void saveLog() {
        try {
             throw new LoggerException(); 
        }catch(Exception ex) {
            origin = ex.getStackTraceString();
            entries.add(new Log_Entry_Event__e(Transaction_Id__c = Request.getCurrent().getRequestId(),
                                               Message__c = 'File Logger - Saving ' + (entry - 1) + ' via Event Bus.',
                                               Entry__c = entry++,
                                               Level__c = 'DEBUG',
                                               Type__c = 'LogDetail',
                                               Callouts__c = LIMITS.getCallouts(),
                                               CPU_Time__c = LIMITS.getCpuTime(),
                                               DML_Statements__c = LIMITS.getDMLStatements(),
                                               Heap_Size__c = LIMITS.getHeapSize(),
                                               SOQL_Queries__c = LIMITS.getQueries(),
                                               SOSL_Queries__c = LIMITS.getSoslQueries(),
                                               Aggregate_Queries__c = LIMITS.getAggregateQueries(),
                                               Async_Calls__c = LIMITS.getAsyncCalls(),
                                               DML_Rows__c = LIMITS.getDMLRows(),
                                               Email_Invocations__c = LIMITS.getEmailInvocations(),
                                               Future_Calls__c = LIMITS.getFutureCalls(),
                                               Queueable_Jobs__c = LIMITS.getQueueableJobs(),
                                               Query_Rows__c = LIMITS.getQueryRows(),
                                               Query_Locator_Rows__c = LIMITS.getQueryLocatorRows(),
                                               Callouts_Limit__c = Limits.getLimitCallouts(),
                                               CPU_Time_Limit__c = Limits.getLimitCpuTime(),
                                               DML_Statements_Limit__c = Limits.getLimitDMLStatements(),
                                               Heap_Size_Limit__c = Limits.getLimitHeapSize(),
                                               SOQL_Queries_Limit__c = Limits.getLimitQueries(),
                                               SOSL_Queries_Limit__c = Limits.getLimitSoslQueries(),
                                               Aggregate_Queries_Limit__c = LIMITS.getLimitAggregateQueries(),
                                               Async_Calls_Limit__c = LIMITS.getLimitAsyncCalls(),
                                               DML_Rows_Limit__c = LIMITS.getLimitDMLRows(),
                                               Email_Invocations_Limit__c = LIMITS.getLimitEmailInvocations(),
                                               Future_Calls_Limit__c = LIMITS.getLimitFutureCalls(),
                                               Queueable_Jobs_Limit__c = LIMITS.getLimitQueueableJobs(),
                                               Query_Rows_Limit__c = LIMITS.getLimitQueryRows(),
                                               Query_Locator_Rows_Limit__c = LIMITS.getLimitQueryLocatorRows(),
                                               Component_Type__c = componentType,
                                               Origin__c = origin));
            if(!entries.isEmpty()) {
                EventBus.publish(entries);
                clearAll();
            }
        }
    }
    
    @InvocableMethod(label='Save Log' description='Used to all log in current transaction' iconName='slds:standard:timesheet_entry')
    public static void saveFlowLog() {
        try {
             throw new LoggerException(); 
        }catch(Exception ex) {
            origin = ex.getStackTraceString();
            entries.add(new Log_Entry_Event__e(Transaction_Id__c = Request.getCurrent().getRequestId(),
                                               Message__c = 'File Logger - Saving ' + (entry - 1) + ' via Event Bus.',
                                               Entry__c = entry++,
                                               Level__c = 'DEBUG',
                                               Type__c = 'LogDetail',
                                               Callouts__c = LIMITS.getCallouts(),
                                               CPU_Time__c = LIMITS.getCpuTime(),
                                               DML_Statements__c = LIMITS.getDMLStatements(),
                                               Heap_Size__c = LIMITS.getHeapSize(),
                                               SOQL_Queries__c = LIMITS.getQueries(),
                                               SOSL_Queries__c = LIMITS.getSoslQueries(),
                                               Aggregate_Queries__c = LIMITS.getAggregateQueries(),
                                               Async_Calls__c = LIMITS.getAsyncCalls(),
                                               DML_Rows__c = LIMITS.getDMLRows(),
                                               Email_Invocations__c = LIMITS.getEmailInvocations(),
                                               Future_Calls__c = LIMITS.getFutureCalls(),
                                               Queueable_Jobs__c = LIMITS.getQueueableJobs(),
                                               Query_Rows__c = LIMITS.getQueryRows(),
                                               Query_Locator_Rows__c = LIMITS.getQueryLocatorRows(),
                                               Callouts_Limit__c = Limits.getLimitCallouts(),
                                               CPU_Time_Limit__c = Limits.getLimitCpuTime(),
                                               DML_Statements_Limit__c = Limits.getLimitDMLStatements(),
                                               Heap_Size_Limit__c = Limits.getLimitHeapSize(),
                                               SOQL_Queries_Limit__c = Limits.getLimitQueries(),
                                               SOSL_Queries_Limit__c = Limits.getLimitSoslQueries(),
                                               Aggregate_Queries_Limit__c = LIMITS.getLimitAggregateQueries(),
                                               Async_Calls_Limit__c = LIMITS.getLimitAsyncCalls(),
                                               DML_Rows_Limit__c = LIMITS.getLimitDMLRows(),
                                               Email_Invocations_Limit__c = LIMITS.getLimitEmailInvocations(),
                                               Future_Calls_Limit__c = LIMITS.getLimitFutureCalls(),
                                               Queueable_Jobs_Limit__c = LIMITS.getLimitQueueableJobs(),
                                               Query_Rows_Limit__c = LIMITS.getLimitQueryRows(),
                                               Query_Locator_Rows_Limit__c = LIMITS.getLimitQueryLocatorRows(),
                                               Component_Type__c = componentType,
                                               Origin__c = flowAPIName));
            if(!entries.isEmpty()) {
                EventBus.publish(entries);
                clearAll();
            }
        }
    }
    
    private static void clearAll() {
        entries.clear();
    }
    
    public class LoggerException extends Exception {
        
    }
}